[tool.poetry]
name = "repltable"
version = "0.1.3"
description = "Table support for the replit database"
authors = ["terabyte. <mikey@mikeyo.ml>"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.7b0"
bandit = "^1.7.0"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
